project:
  type: website
  output-dir: docs

website:
  title: "The Tave"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - blog.qmd
      - dashboard.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: source

