project:
  type: website
  output-dir: docs

website:
  title: "The Tave"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - blog.qmd
      - dashboard.qmd
      
  page-footer: 
    left: "Â© 2024-2026, Anni Tave Overlander" 
    right: 
      - icon: github
        href: https://github.com/the-tave

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: source

